zbrateam/Zebra

Zebra/Console/ZBConsoleViewController.m

The Chimera jailbreak brought a new way to respring called sbreload.  I took advantage of that and Implemented it into Zebra. Don't worry, I also made it compatible with the old respring if the sbreload binary isn't found on the device.

Implement new sbreload command for a faster respring

---

Zebra/Packages/Controllers/ZBPackageDepictionViewController.m
Zebra/Packages/Controllers/ZBPackageListTableViewController.m
Zebra/Packages/Helpers/ZBPackage.h
Zebra/Packages/Helpers/ZBPackage.m
Zebra/Queue/ZBQueue.m
Zebra/Queue/ZBQueueType.h
Zebra/UIColor+GlobalColors.h

In this pull request, users will be able to swipe right-to-left on a package cell to perform certain actions directly without having to go through its depiction page. Design is not yet finalized, users will see actions as text blocks.
One slight issue is user feedback, once they perform, let's say, install action, they won't know if the package has already been queued up until they go to Packages tab and tap on Queue button at top-left. There is no indicator in a package cell Like SwipeForMore, the core design is to not show the queue page, allowing users to go through packages quicker.
Also, this pull request attempts to fix logic in "Modify" button in the package depiction page. Some packages can only be removed, when in fact, they have an appropriate repo and clearly not local …

SwipeForMore-like feature for Zebra.

---

Zebra/Queue/ZBQueue.m

This fixes a bug when sometimes packages won't show in the queue.

[Queue] No, we just remove all the entries of the dictionary's keys

---

Zebra/Parsel/dict.c
Zebra/Parsel/parsel.c

This will fix startup crash due to incorrect reading of package's long description.

[Parsel] Correctly parse the package's long description.

---

Zebra/Packages/Controllers/ZBPackageDepictionViewController.m
Zebra/Packages/Helpers/ZBPackage.h
Zebra/Repos/Controllers/ZBRepoPurchasedPackagesTableViewController.m

This PR includes the following:
- Language Header in depictions
- Payment-Provider header with the value of API (`Payment_Provider: API`) to inform the repo that we support payments without needing to be redirected from the webview
- You can now view Gesto in purchases, need to fix purchasing it.

[Depictions] Send the locale language and Inform the repos that we support payments

---

layout/DEBIAN/postinst

Fixes #141 where setting permissions fails on /var/mobile/Documents if the directory does not exist.

Create Documents directory if it doesn't already exist (fixes #141)

---

Zebra/Repos/Controllers/ZBRepoListTableViewController.m

Fixing PR because old was from a fork that was outdated. Sorry for the dupe!
This basically starts a blacklist of common social media, media links that people may have saved!

Start Repo URL Blacklist On Clipboard Manager

---

Makefile
Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m

Previously, the WKWebView in depictions would scroll in its own WKScrollView while loading, instead of scrolling the entire table view. This was due to some faulty logic where the webview was added as a subview of the tableview, **and** as the footer. This fixes that issue (and also gets theos to kill Zebra on install).

Fix webview scrolling in depictions

---

Zebra/Tabs/Search/ZBSearchViewController.m

Noticed that queries wouldn't show up when having a space before or after the query.

Trim extra whitespace from search queries.

---

Zebra/Queue/ZBQueue.h
Zebra/Queue/ZBQueue.m
Zebra/Queue/ZBQueueViewController.m
Zebra/Tabs/Packages/Views/ZBPackageTableViewCell.m

I also changed some other places in the codebase to make
this more consistent (e.g. remove NSValue stuff).
I also simplified some code in ZBQueue.m, and removed
the stringkey-to-ZBQueueType conversion methods.
Related to #393 and #394

Use NSNumber for key in -[ZBQueue managedQueue]

---

Zebra/Base.lproj/Localizable.strings
Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m

Got rid of the string keys in `infos`, we now use the enum instead.
This class could be cleaned up a bit more...
Fixes #407

[Localization] Cleanup ZBPackageDepictionViewController

---

Makefile

After the previous PR, I started searching for a possible fix for this as you wanted the build number along the package version, so I found a thread in reddit where /u/DHowett (the original dev for theos) explained the different Packge Version Variables used by theos and he was recommending this way to have an incrementing build number along with the base version in order to avoid the deprecation warning. Hope it will be useful. I personally tested it and it succesfully compiles different debs with incrementing build numbers.
P.S. Sorry if I am creating stupid PR's. Keep up the good work.

Possible deprecation warning fix for theos package version

---

Zebra/Tabs/Search/ZBSearchViewController.m

Small suggestion for the SearchVC scroll behaviour.
Indeed, this will resign the first responder when the user starts scrolling on the search page.
This change follows the system apps behaviour(settings, contacts, ...) and is especially useful with the "Live Search" setting.

[Search] Set keyboardDismissMode to OnDrag

---

layout/usr/libexec/zebra/startup

This is a somewhat essential fix for the future. Some modern jailbreaks bundle firmware.sh in another package (e.g. darwintools on checkra1n), and I suspect this will be the future. In the case that the jailbreak's bundled firmware.sh has changed, zebra would continue running the old firmware.sh you have bundled. To combat this, I've made the startup script execute firmware.sh from `/usr/libexec/zebra/` only if the script cannot be found in the libexec root. Would likely solve #1008

[Scripts] firmware.sh should run from libexec root if available

---

Zebra/Base.lproj/Localizable.strings
Zebra/Console/ZBConsoleViewController.m
Zebra/Downloads/ZBDownloadManager.m
Zebra/Tabs/Home/Stores/ZBStoresListTableViewController.m
Zebra/Tabs/Sources/Controllers/ZBSourceSectionsListTableViewController.m

**Added:**
- uicache is not available on the simulator
- Authorizing Download for %@
- Couldn't authorize download for %@.
- Reason: %@.
- The Payment API is not supported on less than iOS 11.0
- Error while moving file at %@ to %@
- Could not authenticate
- Logged in as %@
**Removed:**
- Could not complete purchase, no payment secret was found
**Hidden:**
- Hide UUID

[Localization] Add and remove localization strings

---

Zebra/Queue/ZBQueue.m

Fixes the `W: No sandbox user '_apt' on the system, can not drop privileges` warning I got tired of seeing.

[Queue] Silence sandbox user warning on Electra/Chimera

---

Zebra/Tabs/Sources/Helpers/ZBBaseSource.m

This (should?) resolve a TODO regarding edge cases where an entry such as `deb https://diatr.us new` in the packages file would be handled as a dist repo. Also fixes the useless addition of `./` to the end of every normal repo URL when fetching Packages and Release files.

[Sources] Handle a distribution without components

---

Zebra/Queue/ZBQueue.m

Re-added case dependency and conflict type to not to return null for labels
Fix #1140

[Queue] Re-add dependency and conflict type

---

Zebra.xcodeproj/project.pbxproj
Zebra/Headers/UIAlertController+Private.h
Zebra/Tabs/Packages/Helpers/ZBPackage.h
Zebra/Tabs/Packages/Helpers/ZBPackage.m
Zebra/Tabs/Packages/Helpers/ZBPackageActionType.h
Zebra/Tabs/Packages/Helpers/ZBPackageActions.m

Addresses #975 
This PR makes "Install" action for packages that have multiple versions and are not installed shows the version selector. This also brings design change in package action characters, as seen from the screenshots below:
"Downgrade" now uses "↓", leading to having "Install" uses "⤓".
This will also need a new translation for "Select version to install", as seen from the action sheet:
Notice also the separator between the latest version and the other versions. The private API responsible for this is available in iOS 10 onwards.

[Packages] Select version to install option

---

Zebra/Tabs/ZBTabBarController.m
Zebra/Theme/ZBThemeManager.m
Zebra/ZBAppDelegate.m

On iOS 13, the navigation bar is invisible by default until you scroll. No customization needs to be done at all to the navigation bar aside from setting tint colors.
This PR removes any redundant navigation bar appearance or background color customizations.
This also fixes a bug with the queue navigation bar: the navigation bar would stay dark after installing packages because it was set to dark mode and never set back. The simplest solution is to create a new navigation controller each time and release it as needed, instead of trying to manage a back-and-forth state of the same navigation controller. If you'd rather, I can just do that instead of this, though. Either approach works just as well.

Fix navigation bar color on iOS 13

---

Supersling/ent.plist
Zebra/Zebra.entitlements

Context: https://twitter.com/s1guza/status/1264407308693618688
This is expected to fix operations not permitted and apt errors in Zebra for devices running iOS 13.5 jailbroken via unc0ver 5.0.0.
Intended to address #1281

[Entitlements] PoC Additional entitlements for iOS 13.5

---

Zebra/Base.lproj/Main.storyboard
Zebra/Console/ZBConsoleViewController.m

Hi, this PR adds a 3px padding space to the progress text in the console view. IMHO looks like a lot cleaner.
| Before | After |
|--------|------|
| ![Before](https://i.imgur.com/MmOkhwl.png) | ![After](https://i.imgur.com/S9T9qLB.png)

[Console] Add padding on progress text

---

Zebra/Tabs/Sources/Controllers/ZBAddSourceViewController.m
Zebra/Tabs/Sources/Controllers/ZBSourceListTableViewController.m

Changes:
- Disable add button when the text does not fill with valid URL
- Remove "https://" or "http://" when doubled. (Useful when pasting the URL to the text without deleting the auto filled "https://" manually. Fix https://github.com/wstyres/Zebra/issues/1188#issuecomment-636118934
- Auto fill the valid URL from clipboard when opening Zebra using scheme (zbra://sources). Fix https://github.com/wstyres/Zebra/issues/1188#issuecomment-625675843
Fixes #1188

[Source] Improve adding sources

---

Zebra/Tabs/Changes/ZBChangesTableViewController.m

Fix empty community news cells when `community news` was enabled after opening Zebra.

[Changes] Fix empty community news cell

---

Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.xib

This prevents autoplay for media with sound.

[Packages] Prevent autoplay for media with sound

---

Zebra/Tabs/ZBTabBarController.m

Fix a bug where Zebra didn't show a package number that has an update on package tab when opening Zebra sometimes

[Tab] Show package number that has an update

---

Zebra.xcodeproj/project.pbxproj
Zebra/Base.lproj/Localizable.strings
Zebra/Info.plist
Zebra/Notifications/ZBNotificationManager.h
Zebra/Notifications/ZBNotificationManager.m
Zebra/ZBAppDelegate.m
Zebra/fr.lproj/Localizable.strings

This PR is the continuation of #1329. I wasn't happy with my first implementation, so I made another one much simpler.
First I did add the Background Modes / Background Fetch capability.
When the system wakes Zebra from background, I call :
```objc
[databaseManager updateDatabaseUsingCaching:NO userRequested:YES];
```
The ZBNotificationManager class is a database delegate which will be triggered after each database update (including the one triggered by the above line).
If the numberOfUpdates parameter is not 0, it will perform a diff between the last update list and the new one. If there is any difference it will trigger a notification. It makes the implementation completely stateless.
I've been running a build with notifications for about a week now, and the background wakes are really …

[Notifications] Support for push notifications on package updates

---

.github/workflows/build.yml
.github/workflows/release.yml

See this GitHub blog post for more information: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

[Actions] Use the new way to add GNU Make to the PATH variable

---

Zebra/Zebra.entitlements

This fixes an issue with Zebra crashing when used on iOS 14 with the 'Bold Text' option enabled.

[App] Update entitlements to fix crashes on iOS 14

---

Zebra/Downloads/ZBDownloadManager.m
Zebra/Managers/ZBDatabaseManager.m
Zebra/Managers/ZBSourceManager.m
Zebra/Model/ZBBaseSource.h
Zebra/Model/ZBPackage.m
Zebra/Model/ZBSource.m
Zebra/Tabs/Sources/Views/ZBSourcesAccountBanner.m

This PR reimplements and improves the payment API implementation in Zebra by coupling the payment endpoint and featured packages download into the `Release` download that is performed every source refresh. For the payment API, we query the `payment_endpoint` URL for sources that have secure schemes and save the result into the database if there is a payment endpoint available. For featured packages, we simply query the `sileo-featured.json` URL for sources and if there is a file on the other end, we store that the repository supports featured packages in the database for use later.
This is an improvement over the previous implementation where payment endpoints were queried asynchronously with the source refresh which could result in sources having a payment endpoint in the database, but …

Payment API Reimplementation

---

Zebra/Model/ZBPackage.m

The current logic of extracting dependencies from `Depends` line doesn't look correct to me. See this example.
`firmware` alone is not a correct dependency to be listed. After carefully checking the code, I learned that `depends` property of `ZBPackage` may contain leading and/or trailing spaces. I had to strip those whitespaces about during creation of `depends` property.
Additionally, for those dependencies interconnected with `|` operator, it would be more human readable by joining them with ` or ` as you can see below:
Here's an example from another package that has more dependencies, with the new logic applied:

[Package] Improved listing of dependencies

---

Zebra/Managers/ZBPackageManager.m
Zebra/Model/ZBPackageFilter.m
Zebra/UI/Packages/ZBPackageListViewController.m

Currently, if you try to view the packages from a section: Go to Sources tab > Choose any source > Choose any section that is not "All Packages", all you see is a blank page. This is because `-[ZBPackageManager filterPackages:withFilter:]` would respect `filter`'s `compoundPredicate` and return empty results as `[NSPredicate predicateWithFormat:@"name contains[cd] %@", _searchTerm];` would always yield false.
This PR only applies search term predicate when the search term is not empty.

[Packages] Display all packages in a corresponding section when there is no search query

---

Zebra/Managers/ZBDatabaseManager.m
Zebra/Managers/ZBPackageManager.h
Zebra/Managers/ZBPackageManager.m
Zebra/UI/Packages/ZBPackageListViewController.m

With the database improvements, Zebra was often moving too fast in order to keep up with several database reads/writes at once. This PR attempts to slow things down a bit so that sequential reads/writes are preformed on the database and hopefully solves any crashes with database memory access.
In order to fix database corruptions in version 1 of the database, we force a migration to version 2.
Aims to solve #1682, #1667, and #1657

Synchronize database transactions

---

Zebra/Managers/ZBDatabaseManager.h
Zebra/Managers/ZBDatabaseManager.m
Zebra/Managers/ZBPackageManager.h
Zebra/Managers/ZBPackageManager.m
Zebra/Tabs/Packages/Controllers/ZBPackagesByAuthorTableViewController.m
Zebra/UI/Search/ZBSearchViewController.m

Addresses #1654 
This PR adds a new query statement type: `ZBDatabaseStatementTypeSearchForPackageByAuthorNameAndEmail`. Here, you supply the full author name and email, unlike `ZBDatabaseStatementTypeSearchForPackageByAuthorName` that accepts a partial string of the likes of the author name.
This PR removes a now obsoleted method `-packagesByAuthorWithName:email:`and replaces it with the existing method with an additional `email` parameter known as `-searchForPackagesByAuthorWithName:email:completion:`.

[Packages] Fix packages by author returning empty list from Depiction page

---

Zebra/Managers/ZBDatabaseManager.h
Zebra/Managers/ZBDatabaseManager.m
Zebra/Managers/ZBPackageManager.h
Zebra/Managers/ZBPackageManager.m
Zebra/Tabs/Packages/Helpers/ZBPackageActions.m

This pull request aims to resolve some issues with the package swipe actions:
- Fix the crash when triggering a swipe action on the packages tab
- Always base the change calculations on the installed version of the package.
- Reimplement the package version choice menu to fix null string and to ensure that the package is downloaded from the correct source.

[Packages] Various swipe action fixes

---

Zebra/Model/ZBPackage.m
Zebra/Model/ZBSource.h
Zebra/Model/ZBSource.m
Zebra/UI/Sources/ZBSourceViewController.m

This PR aims to fix a small bug where a payment secret could not be found from a source and Zebra could not download a package. The behavior is to sign out of the source and try the sign in again but Zebra does not check for payment secrets when the user is already signed in. This bug is solved by forcing the source to sign out if it is signed in so that it can re obtain the payment secret.

[Sources] Small payment API fixes

---

Zebra/UI/Search/ZBSearchViewController.m

Sometimes when you keep searching for packages from Search tab. This crash may occur:
```
0       libobjc.A.dylib               	0x1a90a3dd8 0x1a9080000 + 0x23dd8	// objc_release + 0x8
1       CoreFoundation                	0x194c3fb04 0x194c03000 + 0x3cb04	// __RELEASE_OBJECTS_IN_THE_ARRAY__ + 0x70
2       CoreFoundation                	0x194c05ab8 0x194c03000 + 0x2ab8	// -[__NSArrayM dealloc] + 0x110
3     + Zebra (*)                     	0x104cf37d8 0x104cac000 + 0x477d8	// -[ZBBasePackage .cxx_destruct] + 0x54
4       libobjc.A.dylib               	0x1a9085ae0 0x1a9080000 + 0x5ae0	// object_cxxDestructFromClass(objc_object*, objc_class*) + 0x70
5       libobjc.A.dylib               	0x1a909b8a4 0x1a9080000 + 0x1b8a4	// objc_destructInstance + 0x58
6       libobjc.A.dylib …
```

[Search] Prevent multiple search results updates (UI-wise)

---

Zebra/Managers/ZBDatabaseManager.m
Zebra/Managers/ZBSourceManager.m
Zebra/Model/ZBBasePackage.m

The way the packages search works now does not take into account the same packages but from different sources. One is installed, hence its source is local. The other is a generic one which has a correct source, more metadata and can be managed correctly.
In this PR, every kind of packages search will be gated by the aforementioned filtering.
Moreover, the other reason of not being to find a download URL of a package to be installed is when the package's `source` is `nil` - and the root cause is `sourceMap` in `ZBSourceManager` is `nil` as we invoke `- (ZBSource *)sourceWithUUID:(NSString *)UUID` method. This PR ensures that this method has access to non-nil source map.
Closes #1665

[Search, Sources] Filter manage-able versions of packages in the packages search results

---

Zebra/Model/ZBPackage.m

There are lines in `ZBPackage.m` that look like this:
```
NSString *latestVersion = allVersions[0];
```
This assumption is wrong, unless you can guarantee that `-[ZBPackage allVersions]` returns a sorted array of packages by version - the latest version is the first.
Impact: When you browse to a package from Sources tab, you may not get the latest version of the package because of the wrong assumption in code mentioned above.

[Packages] Sort `-[ZBPackage allVersions]`

---

Zebra/UI/Search/ZBSearchViewController.m

A crash may occur from continuously typing in a search input as reloading table action will be invoked multiple times.

[Search] Prevent race condition in packages search

---

Zebra/Managers/ZBDatabaseManager.m

An observation yields that there are unused release and packages files (those that have their corresponding repository removed) lying around. This could create undefined behaviors.

[Sources] Remove lists folder on Clear Sources Cache

---

Zebra/Helpers/utils.c
Zebra/Helpers/utils.h
Zebra/Managers/ZBDatabaseManager.m

Take iSecureOS package for example. Its identifier recently has changed to be `com.geosn0w.iSecureOS`, where `com.geosn0w.isecureos` was the previous. Zebra treats them as different packages. Cydia does not.

[Packages] Make package identifiers lowercase in DB

---

.github/workflows/build.yml

This pull request updates the build workflow to use the latest version of the checkout action and changes the fetching of the submodules to `true` as we don't need the SDWebImage and LNPopupController submodules. It also fixes the commit used for the Plains submodule.

[Actions] Use newer checkout action in build

---

Zebra/UI/Sources/ZBSourceListViewController.mm

Fixes tapping on the first source opening the error log
Disables tapping on failed sources (selectionStyle none doesn't seem to work)

[Sources] Fix tapping first source and disable tapping on failed sources

---

Zebra/Tabs/Home/Settings/Display/ZBDisplaySettingsTableViewController.m
Zebra/Tabs/Sources/Controllers/ZBSourceSectionsListTableViewController.m
Zebra/Theme/ZBThemeManager.m

- (iOS 12-) Fixed certain elements not changing color when the theme has changed.
- Prevented triggering theme change when tapping on pure dark mode cell.

[theme] Toggle system appearance seamlessly

---

Zebra/Tabs/Home/Community Sources/ZBCommunitySourcesTableViewController.m
Zebra/Tabs/Home/Settings/Filters/ZBFilterSettingsTableViewController.m
Zebra/Tabs/Sources/Helpers/ZBBaseSource.m
Zebra/ZBDevice.h
Zebra/ZBDevice.m

Changes in this pull request:
- **Where:** ZBFilterSettingsTableViewController.m:346
- **Cause:** indexPath.section off by 1 due to adding the 'Show Incompatible Packages' option
- **Fix:** Change section numbers in the switch case
- **Where:** ZBDevice.m:253
- **Cause:** Was set as `[@"userspace", @"reboot"]`
- **Fix:** Change arguments to `[@"reboot", @"userspace"]`
- **Where:** ZBBaseSource.m:178
- **Cause:** `iphoneos-arm64-rootless` does not exist for CF 1900
- **Fix:** Use `dist/CFVER` for iOS 16 and above
On rootful, palera1n uses strap.palera.in as it's dist repo, so it will show that instead of Procursus
Also have fixed/added a few items in jailbreak detection

Collection of small bug fixes
