Zebra/Home/ZBWebViewController.m
I added the ability to share your sources and packages. I put the share button on the left of the home page.  When you navigate to a url on that page the share button will go away temporarily so it doesn't get in your way. It comes back when you go back to the home page.
=> Added ability to share/export sources and installed packages

Zebra/Packages/Controllers/ZBPackageDepictionViewController.m
This was tested using flex, switching this bool is needed for dynastic as well
=> Fixes Dynastic Download Issues

Zebra/Database/ZBDatabaseManager.m, Zebra/Packages/Controllers/ZBPackageDepictionViewController.m, Zebra/Packages/Controllers/ZBPackageListTableViewController.h, Zebra/Packages/Controllers/ZBPackageListTableViewController.m, Zebra/Packages/Helpers/ZBPackage.m, Zebra/Repos/Controllers/ZBRepoListTableViewController.h, Zebra/Repos/Controllers/ZBRepoListTableViewController.m, Zebra/Repos/Controllers/ZBRepoSectionsListTableViewController.m, Zebra/Repos/Helpers/ZBAddRepoDelegate.h, Zebra/Search/ZBSearchViewController.m
=> [Packages, Repo, Search] URL detection for package long description and Table View Indexes.

Zebra/Console/ZBConsoleViewController.m
The progress bar will now calculate the percentage of all packages being downloaded, since downloads occur simultaneously and we don't want the progress bar to go back and forth.
=> [Console] Progress bar smoothing.

Zebra/Database/ZBDatabaseManager.h, Zebra/Database/ZBDatabaseManager.m, Zebra/Database/ZBRefreshViewController.h, Zebra/Database/ZBRefreshViewController.m, Zebra/Downloads/ZBDownloadManager.h, Zebra/Downloads/ZBDownloadManager.m, Zebra/Tabs/Changes/ZBChangesTableViewController.m, Zebra/Tabs/Home/AlternateIcon/CommunityRepos/ZBCommunityReposTableViewController.m, Zebra/Tabs/Home/Helpers/ZBWebViewController.m, Zebra/Tabs/Packages/Controllers/ZBInstalledFilesTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackagesByAuthorTableViewController.m, Zebra/Tabs/Repos/Controllers/ZBRepoListTableViewController.m, Zebra/Tabs/Repos/Controllers/ZBRepoPurchasedPackagesTableViewController.m, Zebra/Tabs/Repos/Controllers/ZBRepoSectionsListTableViewController.m, Zebra/Tabs/Repos/Helpers/ZBRepoManager.h, Zebra/Tabs/Repos/Helpers/ZBRepoManager.m, Zebra/Tabs/ZBTabBarController.m
- When refreshing sources, Zebra will try to download only the sources the user has just added
- Improved table refresh
- Fixed wrong sources being added if trigged from Community Repos
=> Improved table refresh performance

Zebra/nb.lproj/Localizable.strings
Don't know what was causing the issue so I went ahead and just forked Zebra and fixed the issue from my PC.
=> [Localization] Update Norwegian Bokmål support

Zebra/es.lproj/Localizable.strings
Fixed grammar issues. It's now more comprehensible for a native Spanish speaker, although there might be a few mistakes left. Overall it's mostly correct. **This localization can be also used for Latin American Spanish (es-419)**, the language differences are minimal.
=> [Localization] Updated Spanish translation

Zebra.xcodeproj/project.pbxproj, Zebra/it.lproj/Localizable.strings
Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates
Francesco#3138
How would you like to be credited? (Name, Twitter Link, Website, etc.)
https://twitter.com/mastercreeper66
=> [Localization] Italian translation

Zebra/ru.lproj/Localizable.strings
**This was not created in Xcode.** Yet, I saw that for every localization language there was a separate folder. So I created one for Russian and put modified Localizable.strings into that folder.
=> [Localization] Add Russian localization

Zebra/ru.lproj/Localizable.strings
Fixed some grammar/meaning mistakes in the translation, optimized more for the existing Zebra UI, etc. Shortened some stuff as well so it fits better.
If credit is needed:
Name: iGerman
Twitter: @iGerman00
=> [Localization] Fixed mistakes in Russian localization

Zebra/de.lproj/Localizable.strings
For example credits is translated as danke but danke means thanks.
=> Fixed some grammar on German (Deutsch)

Zebra/fr.lproj/Localizable.strings
Please add "Augustinbv" to credits. He gave me his feedback and helped me to spot translation mistakes.
=> [Localization] Update French translations

Zebra/nl.lproj/Localizable.strings
* Fixed multiple typos
* Used formal language (je -> u, etc.)
* Clearer language
=> Improved Dutch translations

Zebra/de.lproj/Localizable.strings
**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
Yes, already added
**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
Already credited
=> [Localization] Add german localization for confirm button

Zebra/el.lproj/Localizable.strings
Fixes some gramatical errors and uses the English word for repo as it doesn't translate exactly in Greek
=> [Localization] Fixed some gramatical errors (Greek Translation)

Zebra/nb.lproj/Localizable.strings, Zebra/nn.lproj/Localizable.strings
Added translations for line 216 (confirm) and updated 2 translations.
=> Updated Norwegian Translations

Zebra/de.lproj/Localizable.strings
- Made the user-program relation more consistent by using a friend to friend relation like Apple does. (from "Sie" to "du" for "you").
- More German words :) (i.e.: Cache -> Zwischenspeicher; Login -> Anmelden)
- fixed some mistakes and hopefully didn't add any new ones
=> [Localization] Improved the German localisation

Zebra/lt.lproj/Localizable.strings
Updated Lithuanian language to look more aesthetically pleasing, corrected some grammatical errors.
=> [Localization] Updated Lithuanian language

Zebra/tr.lproj/Localizable.strings
Added the new language base to Turkish.
=> Updated Turkish language

Zebra/ru.lproj/Localizable.strings
Feel free to correct my stuff as I might be mistaken on at least 3 lines.
=> [Localization] Updated Russian translations to fit the new Base.strings

Zebra/pt-BR.lproj/Localizable.strings
Updated to fit the new Localizable.strings and also fix for a grammatical error.
=> [Localization] Updated Brazilian Portuguese Translations

Zebra/lt.lproj/Localizable.strings
Updated Lithuanian translation by newly added 'Localizable.strings'.
=> [Localizable.strings] Lithuanian language update

Zebra/ja.lproj/Localizable.strings
Update Japanese localization to reflect changes to base.
=> [Localization] Update Japanese translation

Zebra.xcodeproj/project.pbxproj, Zebra/Tabs/Changes/ZBChangesTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m, Zebra/Tabs/Packages/Helpers/ZBPackage.m, Zebra/Tabs/Packages/Helpers/ZBPackagePartitioner.h, Zebra/Tabs/Packages/Helpers/ZBPackagePartitioner.m, Zebra/Tabs/Packages/Helpers/ZBSortingType.h
Instead of having just "Recent" section, now we separate the packages into the exact dates on which they got installed.
Closes #406
=> [Packages] Sorting using date now shows the exact dates

Zebra/ar.lproj/Localizable.strings, Zebra/cs.lproj/Localizable.strings, Zebra/da.lproj/Localizable.strings, Zebra/de.lproj/Localizable.strings, Zebra/el.lproj/Localizable.strings, Zebra/es.lproj/Localizable.strings, Zebra/fr.lproj/Localizable.strings, Zebra/he.lproj/Localizable.strings, Zebra/hi.lproj/Localizable.strings, Zebra/hr.lproj/Localizable.strings, Zebra/it.lproj/Localizable.strings, Zebra/ja.lproj/Localizable.strings, Zebra/ko.lproj/Localizable.strings, Zebra/lt.lproj/Localizable.strings, Zebra/lv.lproj/Localizable.strings, Zebra/nb.lproj/Localizable.strings, Zebra/nl.lproj/Localizable.strings, Zebra/nn.lproj/Localizable.strings, Zebra/pl.lproj/Localizable.strings, Zebra/pt-BR.lproj/Localizable.strings, Zebra/pt.lproj/Localizable.strings, Zebra/ru.lproj/Localizable.strings, Zebra/sk.lproj/Localizable.strings, Zebra/sr.lproj/Localizable.strings, Zebra/sv.lproj/Localizable.strings, Zebra/th.lproj/Localizable.strings, Zebra/tr.lproj/Localizable.strings, Zebra/vi.lproj/Localizable.strings, Zebra/zh-Hans.lproj/Localizable.strings, Zebra/zh-Hant.lproj/Localizable.strings
This PR will remain open until the next beta is released to capture all translations made.
=> [Localization] 1.0~beta26 translations

Zebra/de.lproj/Localizable.strings
There are some minor issues with the german translation. This PR fixes some.
=> Improved german translation

layout/usr/libexec/zebra/startup
I hope this helps with the dependency issues.
=> [Scripts] Fix bash syntax in startup script

Zebra/cs.lproj/Localizable.strings, Zebra/da.lproj/Localizable.strings, Zebra/de.lproj/Localizable.strings, Zebra/es.lproj/Localizable.strings, Zebra/hi.lproj/Localizable.strings, Zebra/hr.lproj/Localizable.strings, Zebra/it.lproj/Localizable.strings, Zebra/ja.lproj/Localizable.strings, Zebra/ko.lproj/Localizable.strings, Zebra/lt.lproj/Localizable.strings, Zebra/lv.lproj/Localizable.strings, Zebra/nl.lproj/Localizable.strings, Zebra/ru.lproj/Localizable.strings, Zebra/sk.lproj/Localizable.strings, Zebra/tr.lproj/Localizable.strings
This PR will remain open until the next version is released to capture all translations made.
=> [Localization] New Translations

Zebra/zh-Hant.lproj/Localizable.strings
I use same term of translation as Cydia, so the users can recognize the translation easier.
I also posted comments in crowdin.
=> [Localization] Update Chinese (Traditional) translations

Zebra/Database/ZBDatabaseManager.m, Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m
=> Display installed version of packages in update section, and latest when tapped

Zebra/cs.lproj/Localizable.strings, Zebra/da.lproj/Localizable.strings, Zebra/es.lproj/Localizable.strings, Zebra/fr.lproj/Localizable.strings, Zebra/he.lproj/Localizable.strings, Zebra/ja.lproj/Localizable.strings, Zebra/pt-BR.lproj/Localizable.strings, Zebra/sk.lproj/Localizable.strings, Zebra/th.lproj/Localizable.strings, Zebra/tr.lproj/Localizable.strings, Zebra/zh-Hans.lproj/Localizable.strings
=> [Localization] 1.0.6 Translations

Zebra/Base.lproj/Localizable.strings, Zebra/Console/ZBConsoleViewController.m, Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m, Zebra/ZBSettings.h
=> [Console] Implement finish automatically

Zebra/cs.lproj/Localizable.strings, Zebra/da.lproj/Localizable.strings, Zebra/pt.lproj/Localizable.strings, Zebra/sr.lproj/Localizable.strings, Zebra/vi.lproj/Localizable.strings, Zebra/zh-Hant.lproj/Localizable.strings
=> [Localization] 1.0.x Translations

Zebra/Console/ZBConsoleViewController.m, Zebra/Tabs/Sources/Helpers/ZBSourceManager.m
- Remove duplicate known repo
- Move the delay for automatically finish to an instance variable
=> [Meta] Cleanup

Zebra/Base.lproj/Localizable.strings, Zebra/Tabs/Home/Settings/Display/Accent Color/ZBAccentColorTableViewController.m, Zebra/Tabs/Home/Settings/Display/ZBSettingsDisplayTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m
More translations to do!
Removed duplicate string.
I arranged it to make it cleaner.
Maybe we might have to re-translate some strings. (I hope not)
By the way what's "Modiy"
=> Added more localization and fixed typo

Zebra/Tabs/Home/Settings/Display/Accent Color/ZBAccentColorTableViewController.m, Zebra/Theme/ZBThemeManager.m
Fixes the tint color selection bug and returned the system tint color for depictions.
=> Color bug fixes

Zebra/Database/ZBDatabaseManager.m, Zebra/Tabs/Packages/Helpers/ZBProxyPackage.m
=> Deduplicate packages search results (Version 1.1)

Zebra/Base.lproj/Localizable.strings, Zebra/Database/ZBDatabaseManager.m, Zebra/Tabs/Search/ZBSearchTableViewController.m, Zebra/Tabs/Sources/Controllers/ZBSourceListTableViewController.m
=> Added untranslated strings

Zebra/Tabs/Changes/ZBChangesTableViewController.m, Zebra/Tabs/Home/Wish List/ZBWishListTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.h, Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m, Zebra/Tabs/Packages/Helpers/ZBPackageActionsManager.h, Zebra/Tabs/Packages/Helpers/ZBPackageActionsManager.m, Zebra/Tabs/Search/ZBSearchResultsTableViewController.m
Added Haptic Touch previewing with menu actions. Also added support for previewing wishlist items.
Closes #764
=> Haptic Touch context menus

Zebra/Tabs/Changes/ZBChangesTableViewController.m, Zebra/Tabs/Home/Wish List/ZBWishListTableViewController.m, Zebra/Tabs/Home/ZBHomeTableViewController.m, Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m, Zebra/Tabs/Search/ZBSearchResultsTableViewController.m
Added Haptic Touch context menu support for homepage.
Closes #566
Fixed downgrade alertVC not presenting in Wish List and Search.
Fixed missing weakSelf occurrences from PR #942.
=> Homepage context menus and fixes

Zebra/Database/ZBDatabaseManager.h, Zebra/Database/ZBDatabaseManager.m, Zebra/Parsel/parsel.c, Zebra/Tabs/Changes/ZBChangesTableViewController.m, Zebra/Tabs/Sources/Controllers/ZBRepoSectionsListTableViewController.m
Package filtering feature can be accessed from any section readout of any sources, changes are source-specific.
Known limitation: Changes to filtering requires refresh in Changes tab.
Closes #868
=> Implement packages filtering by section

Zebra/Base.lproj/Localizable.strings, Zebra/Downloads/ZBDownloadManager.m, Zebra/Queue/ZBQueueViewController.m, Zebra/Tabs/Home/Settings/Advanced/ZBAdvancedSettingsTableViewController.m, Zebra/Tabs/Sources/Controllers/ZBSourceSelectTableViewController.m
=> [Localization] Add missing strings

Zebra/Base.lproj/Localizable.strings, Zebra/Tabs/Sources/Views/ZBSourcesAccountBanner.m, Zebra/ZBAppDelegate.m
=> [Localization] Add missing strings and fix typo

.github/workflows/build.yml, .github/workflows/release.yml, .travis.yml
Might speed up the build a bit
=> [Actions] Don't clone theos' commit history (shallow clone)

Firmware/DeviceInfo.h, Firmware/DeviceInfo.m, Firmware/Firmware.m, Firmware/main.m
- Add addional error handling
- Consolidate error handling
- Improve variable names
- Code cleanup
=> [Firmware] Refactoring

Zebra/Tabs/Sources/Helpers/ZBBaseSource.m
=> [Sources] Verify Packages media type during verification

Zebra/Base.lproj/Localizable.strings, Zebra/Console/ZBConsoleViewController.m, Zebra/Database/ZBDatabaseManager.m, Zebra/Database/ZBDependencyResolver.m, Zebra/ZBAppDelegate.m
**Added strings:**
- Could not complete %@ process. Reason: %@.
- Please restart Zebra and see if the issue still persists. If so, please file an issue on GitHub.
- This device is simulated, here are the packages that would be modified in this stage:
- Error while creating documents directory: %@.
- Error while creating lists directory: %@.
- Error while creating sources.list: %@.
- Error while creating debs directory: %@.
- \"%@\" conflicts with %@
=> [Localization] Add more strings for localization

Zebra/Base.lproj/Localizable.strings, Zebra/Tabs/Sources/Views/ZBSourcesAccountBanner.m
Added:
- Local File
- Install All
Changed:
- "Logged in ~" to "Signed in ~".
Use the same string as the store page in home tab
=> [Localization] Add missing strings 

Zebra/Tabs/Packages/Helpers/ZBProxyPackage.m
=> Check ZBProxyPackage installation status against the database

README.md
Add instruction to install fakeroot
=> [README] Add instruction to install fakeroot

Zebra/Tabs/Home/Settings/Filters/ZBFilterSettingsTableViewController.m, Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m
=> Fix settings UI bugs

Zebra/Base.lproj/Localizable.strings
Added
- Latest
- Select a version to install:
Removed
- Hide UDID
=> [Localization] Add new strings from #1175

Zebra/Tabs/Changes/ZBChangesTableViewController.m
=> [News] Strip tags from news titles

.github/workflows/build.yml, .github/workflows/release.yml
- Improve and move attaching package to release
- Build and attach IPA to release
- General cleanup
- Use token instead of ssh key
=> [Actions] Various improvements

Zebra/Base.lproj/Localizable.strings
Added
- Always Install Latest
- Always install the most recent version of a package if it is not already installed.
from d82c186a8127ddf397187b5a65832ef083a06922
=> [Localization] Add new strings

Zebra/Base.lproj/Localizable.strings, Zebra/Tabs/Sources/Controllers/ZBSourceListTableViewController.m
Implements the scroll to source feature from #1204
=> [Sources] View already added source

Zebra/Tabs/Sources/Helpers/ZBSource.m
=> [Source] Make Zebra's source unremovable

Zebra/Database/ZBDatabaseManager.m
=> [Search] Fix package order in search results

Zebra/Base.lproj/Localizable.strings
Added
- Error while downloading %@: %@
=> [Localization] Add missing string

Zebra/Database/ZBDatabaseManager.m
=> [Search] Fix live search

Zebra/Tabs/Search/ZBSearchTableViewController.m
=> [Search] Add swipe to remove search history

Zebra/Tabs/Sources/Controllers/ZBSourceSectionsListTableViewController.m
=> [Filter] All Package shouldn't be selected

Zebra/Tabs/Home/Settings/Filters/ZBAuthorSelectorTableViewController.m, Zebra/Tabs/Home/Settings/Filters/ZBFilterSettingsTableViewController.m
This PR will fix:
- Don't erase text when users pressed search button.
This PR will also change:
- Disable add button when a new author to block is not selected.
- Dismiss view controller properly when "cancel" are pressed.
- Hide information button on author cells when there are no aliases with the e-mail address.
=> [Filter] Improve filter setting - author

Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m
Fix `Community News` toggle getting disabled when opening `Download Timeout` section
=> [Sources] Add missing breaks in switch statement

Zebra/Tabs/Packages/Controllers/ZBPackageDepictionViewController.m
This adds inline media playback and prevents autoplay for media with sound.
=> [Packages] Allow muted inline media playback

Zebra/Tabs/Sources/Controllers/ZBSourceSectionsListTableViewController.m
Fix a bug that was introduced in #1411
=> [Sources] Fix not opening package list from section list

Zebra/Tabs/Home/Settings/Filters/ZBFilterSettingsTableViewController.m, Zebra/Tabs/Sources/Controllers/ZBSourceSelectTableViewController.h, Zebra/Tabs/Sources/Controllers/ZBSourceSelectTableViewController.m, Zebra/Tabs/Sources/Helpers/ZBSource.h, Zebra/Tabs/Sources/Helpers/ZBSource.m
Selecting multiple sources for filtering should be possible. This PR also fixes #1387.
=> [Filters, Sources] Allow selection of multiple sources, also prevent re-adding

.github/workflows/build.yml, .github/workflows/release.yml, .travis.yml
This fixes the Travis and Actions build failing.
I have filed a bug report with theos here: theos/theos#531 feel free to add to it.
=> [CI] Use theos commit before the next branch was merged

Zebra/Tabs/Sources/Controllers/ZBSourceAddViewController.m
This pull reqeust aims to fix the crash when adding a source through the popup.
It also automatically adds the HTTPS url scheme to the url if it has no scheme or a non HTTP or HTTPS one.
If a source doesn't exist it silently fails, an error message might me useful to reduce user confusion.
=> [Sources] Fix add source popup crash and auto prepend scheme if missing

Zebra/Queue/ZBQueue.m
=> "Fix" apt trying to download a package even if it's a local path

Zebra/Tabs/Sources/Helpers/ZBSourceManager.m
Just a quick fix for not detecting the real jailbreak properly.
Fix #1536
=> [Source] Fix jailbreak detection

Zebra/Tabs/Home/Settings/ZBMainSettingsTableViewController.m, Zebra/ZBSettings.m
Ported from the master branch and updated for 1.2.
Thanks to @wstyres for the original implementation and @eve0415 for the first port for 1.2.
=> [Sources] Add option to configure sources timeout

Zebra/Tabs/Packages/Helpers/ZBPackageActions.m
=> [Package] Fix crash trying to unblock author that has no mail address

Zebra/Database/ZBDatabaseManager.m
=> [Database] Fix searching for packages by author name

Zebra/Simulator Resources/Installed.pack
Latest Procursus bootstrap as of the date of this commit.
=> [Project] Update simulator installed packages

Zebra/Tabs/Sources/Helpers/ZBSourceManager.m
=> [Sources] Obey source caching flag when refreshing sources

Zebra/Extensions/ZBRefreshableTableViewController.m, Zebra/Managers/ZBSourceManager.h, Zebra/Managers/ZBSourceManager.m, Zebra/Model/ZBBaseSource.h, Zebra/Model/ZBBaseSource.m
Additional minor changes:
- Remove refreshable table vc as source delegate during deallocation
- Fix a few imports
- Use correct format specifier in the base source description
=> [Sources] Notify delegates when cancelling the sources refresh

Zebra/Model/ZBPackageFilter.m
=> [Package] Encode/decode sort order and role properly so that the values are saved correctly

Zebra/Managers/ZBDatabaseManager.h, Zebra/Managers/ZBDatabaseManager.m, Zebra/Tabs/Home/Settings/Filters/ZBAuthorSelectorTableViewController.m
Known limitation: Cannot filter out packages that their author does not provide an email.
Addresses #1656
=> [Filter] Re-implementation of packages filter by author name (rather by email)

Zebra/Database/ZBDependencyResolver.m, Zebra/Managers/ZBDatabaseManager.m, Zebra/Queue/ZBQueue.h, Zebra/Queue/ZBQueue.m
This PR provides some temporary fixes to the current dependency system to work with the new database while the new system is being worked on.
=> Fix dependencies not being fetched

Zebra/Tabs/Home/Settings/Filters/ZBAuthorSelectorTableViewController.m
=> [Filter] Do live search for authors filtering

Zebra/Managers/ZBDatabaseManager.h, Zebra/Managers/ZBDatabaseManager.m, Zebra/Tabs/Home/Settings/Reset/ZBSettingsResetTableViewController.m, Zebra/UI/Migration/ZBMigrationViewController.m
UI may be unfinished, but functionality works. It fixes the packages mixing up bug for me.
Addresses #1663
=> [Sources] Re-enable Reset Sources Cache

Zebra/Managers/ZBDatabaseManager.h, Zebra/Managers/ZBDatabaseManager.m, Zebra/Managers/ZBSourceManager.h, Zebra/Managers/ZBSourceManager.m, Zebra/Tabs/Home/Settings/Filters/ZBSectionSelectorTableViewController.m
=> [Filters] Make filter by sections working

Zebra/UI/Sources/ZBSourceListViewController.m, Zebra/UI/Sources/ZBSourceViewController.m
=> [Sources] Do not push view controller for sources that are not loaded correctly

Zebra/vi.lproj/Localizable.strings
=> Update Vietnamese Translation

Zebra/JSONParsing/ZBRedditPosts.h, Zebra/JSONParsing/ZBRedditPosts.m, Zebra/Tabs/Changes/ZBChangesTableViewController.m
=> [Reddit] Update HTTP Authorization header for getting access token, handle new parameter
